"""Add approval system for runs

Revision ID: 4dfd0f633d72
Revises: 16d4c28c4323
Create Date: 2025-10-23 17:26:09.451472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfd0f633d72'
down_revision = '16d4c28c4323'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_member', sa.Column('is_authorizer', sa.Boolean(), nullable=True))
    op.add_column('run', sa.Column('needs_approval', sa.Boolean(), nullable=True))
    op.add_column('run', sa.Column('approval_due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('run', sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'OVERDUE', name='approvalstatus'), nullable=True))
    op.add_column('run', sa.Column('approval_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'approval_email')
    op.drop_column('run', 'approval_status')
    op.drop_column('run', 'approval_due_date')
    op.drop_column('run', 'needs_approval')
    op.drop_column('project_member', 'is_authorizer')
    # ### end Alembic commands ###
