"""create_plugin_table_properly

Revision ID: 5a2375eaa228
Revises: 9ed8c7958678
Create Date: 2025-10-15 10:26:47.344513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2375eaa228'
down_revision = '9ed8c7958678'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
