"""add_run_comment_table

Revision ID: 5c9ea69a7f29
Revises: d836e47913db
Create Date: 2025-10-16 10:45:04.435688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9ea69a7f29'
down_revision = 'd836e47913db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
