"""add_project_attachment_table

Revision ID: 60c9aa754727
Revises: 5d4ff308ec28
Create Date: 2025-10-20 10:54:43.875608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c9aa754727'
down_revision = '5d4ff308ec28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
