"""Add soft delete fields to Project and Run

Revision ID: 684f7635a335
Revises: 8f4296c854a7
Create Date: 2025-10-12 14:18:06.083110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684f7635a335'
down_revision = '8f4296c854a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('run', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'deleted_at')
    op.drop_column('project', 'deleted_at')
    # ### end Alembic commands ###
