"""add_plugin_table

Revision ID: 9ed8c7958678
Revises: a00b69960672
Create Date: 2025-10-15 10:16:10.380263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed8c7958678'
down_revision = 'a00b69960672'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plugin', 'supported_formats',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('plugin', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('plugin', 'supported_formats',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
