"""add_plugin_management_table

Revision ID: a00b69960672
Revises: c0fefdfe11fa
Create Date: 2025-10-15 09:59:37.399212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00b69960672'
down_revision = 'c0fefdfe11fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
