"""Add roles table for dynamic role management

Revision ID: a60e75f8e59e
Revises: a8c116c03675
Create Date: 2025-10-15 16:49:32.982228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a60e75f8e59e'
down_revision = 'a8c116c03675'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_member', 'role',
               existing_type=postgresql.ENUM('OWNER', 'EDITOR', 'VIEWER', 'member', 'watcher', name='role'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_member', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('OWNER', 'EDITOR', 'VIEWER', 'member', 'watcher', name='role'),
               existing_nullable=False)
    # ### end Alembic commands ###
