"""add_plugin_name_to_projects

Revision ID: c0fefdfe11fa
Revises: 684f7635a335
Create Date: 2025-10-14 13:42:55.013715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0fefdfe11fa'
down_revision = '684f7635a335'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('plugin_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'plugin_name')
    # ### end Alembic commands ###
