'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'
import { usePluginDescriptions } from './plugin-descriptions'

export type Language = 'en' | 'zh'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, any>) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation keys and their values
const translations = {
  en: {
    // Plugins Listing
    'plugins.list.title': 'Analysis Plugins',
    'plugins.list.subtitle': 'Choose an analysis plugin to process your Excel data',
    'plugins.list.createProject': 'Create New Project',
    'plugins.list.loading': 'Loading plugins...',
    'plugins.list.none': 'No plugins available',
    'plugins.list.backToProjects': 'Back to Projects',

    // Plugins Create Project
    'plugins.create.back': 'Back to Plugins',
    'plugins.create.title': 'Create Project with Plugin',
    'plugins.create.subtitle': 'Select a plugin and create a project to start your analysis',
    'plugins.create.stepSelect': '1. Select Analysis Plugin',
    'plugins.create.features': 'Features:',
    'plugins.create.stepConfigure': '2. Configure Project',
    'plugins.create.details': 'Project Details',
    'plugins.create.name': 'Project Name',
    'plugins.create.namePlaceholder': 'Enter project name...',
    'plugins.create.description': 'Description',
    'plugins.create.descriptionPlaceholder': 'Enter project description...',
    'plugins.create.public': 'Make this project public',
    'plugins.create.selected': 'Selected Plugin:',
    'plugins.create.creating': 'Creating Project...',
    'plugins.create.create': 'Create Project & Start Analysis',
    'plugins.create.loading': 'Loading...',

    // Plugin Wizard
    'plugin.wizard.upload': 'Upload Excel File',
    'plugin.wizard.uploadDesc': 'Select and analyze your Excel file',
    'plugin.wizard.selectVariables': 'Select Variables',
    'plugin.wizard.selectVariablesDesc': 'Choose categorical variable for analysis',
    'plugin.wizard.validation': 'Data Validation',
    'plugin.wizard.validationDesc': 'Validate structure, metadata, and data quality',
    'plugin.wizard.boundary': 'Boundary Calculation',
    'plugin.wizard.boundaryDesc': 'Calculate min, max, inc, tick values',
    'plugin.wizard.processing': 'File Processing',
    'plugin.wizard.processingDesc': 'Generate CSV and JSL files',
    'plugin.wizard.run': 'Run Analysis',
    'plugin.wizard.runDesc': 'Monitor your analysis progress',
    'plugin.wizard.selectExcel': 'Select Excel File',
    'plugin.wizard.analyzeFile': 'Analyze File',
    'plugin.wizard.selectCatVar': 'Select Categorical Variable',
    'plugin.wizard.selectCatVarDesc': 'Choose the categorical variable used to group data for analysis.',
    'plugin.wizard.fileAnalysis': 'File Analysis Results:',
    'plugin.wizard.catVar': 'Categorical Variable:',
    'plugin.wizard.catVarHint': 'This variable will be used to group your data in charts.',
    'plugin.wizard.noCatVar': 'No Categorical Variables Found',
    'plugin.wizard.noCatVarDesc': "Couldn't identify categorical variables automatically. Please check the Excel structure or specify manually.",
    'plugin.wizard.continueValidation': 'Continue to Validation',
    'plugin.wizard.validateFile': 'Validate File',
    'plugin.wizard.viewDetails': 'View Details',
    'plugin.wizard.continueBoundary': 'Continue to Boundary Calculation',
    'plugin.wizard.boundaryLong': 'Calculate min, max, inc, and tick values based on your data and specifications.',
    'plugin.wizard.thisStep': 'What this step does:',
    'plugin.wizard.stepAnalyze': 'Analyzes data ranges and USL/LSL specifications',
    'plugin.wizard.stepMinMax': 'Calculates optimal min/max values for charts',
    'plugin.wizard.stepInc': 'Determines appropriate increment (inc) values',
    'plugin.wizard.stepTick': 'Sets tick mark intervals for better visualization',
    'plugin.wizard.calculate': 'Calculate Boundaries',
    'plugin.wizard.boundaryResults': 'Boundary Calculation Results:',
    'plugin.wizard.processingDots': 'Processing...',
    'plugin.wizard.processFiles': 'Process Files',
    'plugin.wizard.running': 'Analysis Running',
    'plugin.wizard.runningDesc': 'Your analysis is now running. You can monitor the progress in the runs section.',
    'plugin.wizard.status': 'Analysis Status',
    'plugin.wizard.clickStart': 'Click "Start Analysis" to begin.',
    'plugin.wizard.runId': 'Run ID',
    'plugin.wizard.runStatus': 'Run status',
    'plugin.wizard.starting': 'Starting...',
    'plugin.wizard.start': 'Start Analysis',
    'plugin.wizard.goToProject': 'Go to Project Dashboard',
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profile',
    'nav.profileSettings': 'Profile Settings',
    'nav.logout': 'Logout',
    'nav.language': 'Language',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.guest': 'Continue as Guest',
    'auth.welcome': 'Welcome back',
    'auth.guestWelcome': 'Welcome back (Guest)',
    'auth.loginTitle': 'Login to Your Account',
    'auth.registerTitle': 'Create New Account',
    'auth.loginSubtitle': 'Sign in to access your projects and analysis results',
    'auth.registerSubtitle': 'Create an account to start analyzing data',
    'auth.signingIn': 'Signing in...',
    'auth.creatingAccount': 'Creating account...',
    'auth.creatingGuest': 'Creating guest session...',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.switchToLogin': 'Switch to Login',
    'auth.switchToRegister': 'Switch to Register',
    'auth.tryAsGuest': 'Try as Guest',
    'auth.guestDescription': 'Experience the platform without creating an account',
    'auth.guestWarning': 'Guest access has limited features and file size restrictions. Create an account for full access.',
    
    // Profile
    'profile.title': 'Profile Settings',
    'profile.subtitle': 'Manage your account settings and preferences',
    'profile.notAvailable': 'Profile Settings Not Available',
    'profile.guestMessage': 'Guest users cannot access profile settings. Please create an account to manage your profile.',
    'profile.goHome': 'Go to Home',
    'profile.tabs.profile': 'Profile',
    'profile.tabs.security': 'Security',
    'profile.tabs.danger': 'Danger Zone',
    'profile.info.title': 'Profile Information',
    'profile.info.subtitle': 'Update your profile information and account details',
    'profile.info.accountId': 'Account ID',
    'profile.info.accountType': 'Account Type',
    'profile.info.memberSince': 'Member Since',
    'profile.info.lastLogin': 'Last Login',
    'profile.info.administrator': 'Administrator',
    'profile.info.regularUser': 'Regular User',
    'profile.info.emailAddress': 'Email Address',
    'profile.info.updateEmail': 'Update Email',
    'profile.info.updating': 'Updating...',
    'profile.security.title': 'Change Password',
    'profile.security.subtitle': 'Update your password to keep your account secure',
    'profile.security.currentPassword': 'Current Password',
    'profile.security.newPassword': 'New Password',
    'profile.security.confirmPassword': 'Confirm New Password',
    'profile.security.changePassword': 'Change Password',
    'profile.security.changingPassword': 'Changing Password...',
    'profile.security.requirements': 'Password Requirements:',
    'profile.security.requirements.minLength': 'At least 8 characters long',
    'profile.security.requirements.different': 'Must be different from your current password',
    'profile.danger.title': 'Danger Zone',
    'profile.danger.subtitle': 'Irreversible and destructive actions',
    'profile.danger.deleteAccount': 'Delete Account',
    'profile.danger.deleteWarning': 'Once you delete your account, there is no going back. This will permanently delete your account and remove all your data from our servers.',
    'profile.danger.deletingAccount': 'Deleting Account...',
    
    // Dashboard
    'dashboard.title': 'Data Analysis Platform',
    'dashboard.welcome': 'Welcome back',
    'dashboard.guestWelcome': 'Welcome back (Guest)',
    'dashboard.subtitle': 'Manage your projects and view your analysis results.',
    'dashboard.stats.totalProjects': 'Total Projects',
    'dashboard.stats.totalRuns': 'Total Runs',
    'dashboard.stats.activeRuns': 'Active Runs',
    'dashboard.projects.title': 'Your Projects',
    'dashboard.projects.newProject': 'New Project',
    'dashboard.projects.noProjects': 'No projects yet',
    'dashboard.projects.noProjectsMessage': 'Create your first project to start analyzing data with JMP.',
    'dashboard.projects.createFirst': 'Create Your First Project',
    'dashboard.projects.createNew': 'Create New Project',
    'dashboard.projects.createSubtitle': 'Create a new project to organize your data analysis tasks',
    'dashboard.projects.projectName': 'Project Name',
    'dashboard.projects.projectDescription': 'Description (Optional)',
    'dashboard.projects.makePublic': 'Make this project public (accessible via URL)',
    'dashboard.projects.creating': 'Creating...',
    'dashboard.projects.createProject': 'Create Project',
    'dashboard.projects.public': 'Public',
    'dashboard.projects.private': 'Private',
    'dashboard.projects.runs': 'runs',
    'dashboard.projects.lastRun': 'Last run',
    'dashboard.projects.viewProject': 'View Project',
    'dashboard.runs.title': 'Recent Runs',
    'dashboard.runs.noRuns': 'No recent runs',
    'dashboard.runs.noRunsMessage': 'Start your first analysis to see run history here.',
    'dashboard.welcomeMessage': 'Manage your projects and view your analysis results.',
    'dashboard.enterProjectName': 'Enter project name',
    'dashboard.enterProjectDescription': 'Enter project description',
    
    // Projects
    'projects.backToDashboard': 'Back to Dashboard',
    'projects.startAnalysis': 'Start New Analysis',
    'projects.startAnalysisSubtitle': 'Upload your CSV data file and JSL script to generate boxplot visualizations',
    'projects.csvFile': 'CSV Data File',
    'projects.jslFile': 'JSL Script File',
    'projects.selectFile': 'Select File',
    'projects.noFileSelected': 'No file selected',
    'projects.startRun': 'Start Analysis',
    'projects.starting': 'Starting...',
    'projects.analysisHistory': 'Analysis History',
    'projects.loadingRuns': 'Loading runs...',
    'projects.noRuns': 'No runs yet',
    'projects.noRunsMessage': 'Upload files and start your first analysis.',
    'projects.runStatus.queued': 'Queued',
    'projects.runStatus.running': 'Running',
    'projects.runStatus.succeeded': 'Succeeded',
    'projects.runStatus.failed': 'Failed',
    'projects.runStatus.canceled': 'Canceled',
    'projects.downloadResults': 'Download Results',
    'projects.viewImages': 'View Images',
    'projects.deleteRun': 'Delete Run',
    'projects.projectDetails': 'Project Details',
    'projects.owner': 'Owner',
    'projects.unknown': 'Unknown',
    'projects.created': 'Created',
    'projects.quickStats': 'Quick Stats',
    'projects.publicSharing': 'Public Sharing',
    'projects.publicSharingSubtitle': 'This project is publicly accessible via URL',
    'projects.publicUrl': 'Public URL',
    'projects.copyLink': 'Copy Public Link',
    'projects.copied': 'Copied to clipboard!',
    'projects.deleteProject': 'Delete Project',
    'projects.deleteConfirm': 'Are you sure you want to delete this project? This action cannot be undone.',
    
    // Messages
    'messages.passwordChanged': 'Password changed successfully',
    'messages.profileUpdated': 'Profile updated successfully',
    'messages.accountDeleted': 'Account deleted successfully',
    'messages.emailRequired': 'Email is required',
    'messages.emailSame': 'Email is the same as current email',
    'messages.passwordRequired': 'All password fields are required',
    'messages.passwordMismatch': 'New passwords do not match',
    'messages.passwordTooShort': 'New password must be at least 8 characters long',
    'messages.currentPasswordIncorrect': 'Current password is incorrect',
    'messages.emailAlreadyExists': 'Email already registered',
    'messages.guestCannotChangePassword': 'Guest users cannot change passwords',
    'messages.guestCannotUpdateProfile': 'Guest users cannot update profile information',
    'messages.adminCannotDelete': 'Admin accounts cannot be deleted',
    'messages.projectCreated': 'Project created successfully!',
    'messages.projectDeleted': 'Project deleted successfully!',
    'messages.runStarted': 'Analysis started successfully!',
    'messages.runDeleted': 'Run deleted successfully!',
    'messages.fileUploaded': 'Files uploaded successfully!',
    'messages.copyFailed': 'Failed to copy to clipboard',
    'messages.downloadFailed': 'Download failed',
    'messages.uploadFailed': 'Upload failed',
    'messages.analysisFailed': 'Analysis failed',
    'messages.authenticationFailed': 'Authentication failed',
    
    // Plugin Cards
    'plugin.card.supportedFormats': 'Supported Formats:',
    'plugin.card.usePlugin': 'Use Plugin',
    'plugin.card.version': 'v',
    
    // Plugin Names and Descriptions
    'plugin.excel2boxplotv1.name': 'Excel to Boxplot V1',
    'plugin.excel2boxplotv1.description': 'Convert Excel files to CSV and JSL scripts with three-checkpoint validation system',
    'plugin.excel2boxplotv2.name': 'Excel to Boxplot V2',
    'plugin.excel2boxplotv2.description': 'Excel to CSV/JSL with V2 column mapping',
    'plugin.excel2processcapability.name': 'Excel to Process Capability',
    'plugin.excel2processcapability.description': 'Convert Excel data to process capability analysis (Cp, Cpk, Pp, Ppk)',
    
    // Plugin Categories
    'plugin.category.analysis': 'Analysis',
    'plugin.category.statistics': 'Statistics',
    
    // Plugin Features
    'plugin.excel2boxplotv1.features.0': 'Three-checkpoint validation system',
    'plugin.excel2boxplotv1.features.1': 'Automatic file fixing for corrupted Excel files',
    'plugin.excel2boxplotv1.features.2': 'Boundary calculation (min, max, inc, tick)',
    'plugin.excel2boxplotv1.features.3': 'CSV and JSL generation',
    'plugin.excel2boxplotv1.features.4': 'Boxplot visualization',
    'plugin.excel2boxplotv2.features.0': 'V2 meta column mapping (Y Variable/DETAIL/Target/USL/LSL/Label)',
    'plugin.excel2boxplotv2.features.1': 'Prefers Stage as categorical variable',
    'plugin.excel2boxplotv2.features.2': 'Three-checkpoint validation (informational)',
    'plugin.excel2boxplotv2.features.3': 'Boundary calculation (min, max, inc, tick)',
    'plugin.excel2boxplotv2.features.4': 'CSV and JSL generation',
    'plugin.excel2processcapability.features.0': 'Process capability analysis',
    'plugin.excel2processcapability.features.1': 'Statistical process control',
    'plugin.excel2processcapability.features.2': 'Capability indices calculation',
    'plugin.excel2processcapability.features.3': 'Control charts generation',
    
    // Admin Plugin Management
    'admin.plugins.title': 'Plugin Management',
    'admin.plugins.subtitle': 'Manage installed plugins and their descriptions',
    'admin.plugins.backToDashboard': 'Back to Dashboard',
    'admin.plugins.install': 'Install',
    'admin.plugins.uninstall': 'Uninstall',
    'admin.plugins.editEnglish': 'Edit English',
    'admin.plugins.editChinese': 'Edit Chinese',
    'admin.plugins.save': 'Save',
    'admin.plugins.cancel': 'Cancel',
    'admin.plugins.addFeature': 'Add Feature',
    'admin.plugins.supportedFormats': 'Supported Formats:',
    'admin.plugins.installed': 'installed',
    'admin.plugins.available': 'available',
    'admin.plugins.features': 'Features:',
    'admin.plugins.name': 'Name',
    'admin.plugins.description': 'Description',
    'admin.plugins.featuresLabel': 'Features',
    'admin.plugins.chineseFeatures': '功能特性:',
    'admin.plugins.chineseName': '名称',
    'admin.plugins.chineseDescription': '描述',
    'admin.plugins.chineseAddFeature': '添加功能',
    'admin.plugins.chineseSave': '保存',
    'admin.plugins.chineseCancel': '取消',
    'admin.plugins.chineseEdit': '编辑中文',
    'admin.plugins.englishEdit': 'Edit English',
    
    // Landing Page
    'landing.title': 'Data Analysis Platform',
    'landing.subtitle': 'Upload your CSV and JSL files to generate beautiful boxplot visualizations with JMP. Real-time processing, interactive galleries, and seamless sharing.',
    'landing.features.easyUpload.title': 'Easy Upload',
    'landing.features.easyUpload.description': 'Drag and drop your CSV and JSL files for instant analysis',
    'landing.features.realTime.title': 'Real-time Processing',
    'landing.features.realTime.description': 'Watch your analysis progress in real-time with live updates',
    'landing.features.share.title': 'Share & Collaborate',
    'landing.features.share.description': 'Share your results with team members or create public links',
    
    // Help
    'help.title': 'Help',
    'help.center': 'Help Center',
    'help.overview': 'Platform Overview',
    'help.gettingStarted': 'Getting Started',
    'help.plugins': 'Available Plugins',
    'help.troubleshooting': 'Troubleshooting',
    'help.support': 'Support & Contact',
    'help.navigation': 'Navigation',
    'help.back': 'Back',
    
    // Dashboard Additional Translations
    'dashboard.createProject.title': 'Create New Project',
    'dashboard.createProject.subtitle': 'Create a new project to organize your data analysis tasks',
    'dashboard.createProject.projectName': 'Project Name',
    'dashboard.createProject.description': 'Description (Optional)',
    'dashboard.createProject.makePublic': 'Make this project public (accessible via URL)',
    'dashboard.createProject.creating': 'Creating...',
    'dashboard.createProject.create': 'Create Project',
    'dashboard.createProject.cancel': 'Cancel',
    'dashboard.stats.activeProjects': 'Active Projects',
    'dashboard.stats.totalAnalyses': 'Total Analyses',
    'dashboard.stats.currentlyProcessing': 'Currently Processing',
    'dashboard.projects.noProjects.title': 'No projects yet',
    'dashboard.projects.noProjects.message': 'Create your first project to start analyzing data with JMP. Upload Excel files and generate beautiful visualizations.',
    'dashboard.plugins.title': 'Analysis Plugins',
    'dashboard.plugins.excelPlugins.title': 'Excel Analysis Plugins',
    'dashboard.plugins.excelPlugins.description': 'Convert Excel files to statistical analysis and visualizations',
    'dashboard.plugins.excelPlugins.viewAll': 'View All Plugins',
    'dashboard.plugins.quickAnalysis.title': 'Quick Boxplot Analysis',
    'dashboard.plugins.quickAnalysis.description': 'Upload Excel file and generate boxplot analysis instantly',
    'dashboard.plugins.quickAnalysis.start': 'Start Boxplot Analysis',
    'dashboard.recentRuns.title': 'Recent Runs',
    
    // Project Membership Management
    'membership.title': 'Project Members',
    'membership.subtitle': 'Manage project members and their roles.',
    'membership.viewOnly.subtitle': 'You can view project members but cannot manage them.',
    'membership.tabs.current': 'Current Members',
    'membership.tabs.add': 'Add Members',
    'membership.searchUsers': 'Search Users',
    'membership.searchPlaceholder': 'Search by email or name...',
    'membership.role': 'Role',
    'membership.filterDepartment': 'Filter by Department',
    'membership.filterBusinessGroup': 'Filter by Business Group',
    'membership.allDepartments': 'All departments',
    'membership.allBusinessGroups': 'All business groups',
    'membership.searchResults': 'Search Results',
    'membership.searching': 'Searching...',
    'membership.noUsersFound': 'No users found',
    'membership.enterSearchTerm': 'Enter a search term to find users',
    'membership.alreadyMember': 'Already Member',
    'membership.add': 'Add',
    'membership.owner': 'Owner',
    'membership.member': 'Member',
    'membership.watcher': 'Watcher',
    'membership.removeMember': 'Remove Member',
    'membership.removeConfirm': 'Are you sure you want to remove {name} from this project?',
    'membership.remove': 'Remove',
    'membership.roleUpdated': 'Member role updated successfully',
    'membership.memberRemoved': 'Member removed successfully',
    'membership.memberAdded': 'Added {name} as {role}',
    'membership.loadMembersFailed': 'Failed to load members',
    'membership.searchUsersFailed': 'Failed to search users',
    'membership.addMemberFailed': 'Failed to add member',
    'membership.updateRoleFailed': 'Failed to update member role',
    'membership.removeMemberFailed': 'Failed to remove member',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.subtitle': 'Stay updated with project activities and team changes.',
    'notifications.markAllRead': 'Mark All Read',
    'notifications.loading': 'Loading notifications...',
    'notifications.noNotifications': 'No notifications yet',
    'notifications.noNotificationsMessage': 'You\'ll see project updates here',
    'notifications.justNow': 'Just now',
    'notifications.minutesAgo': '{minutes}m ago',
    'notifications.hoursAgo': '{hours}h ago',
    'notifications.daysAgo': '{days}d ago',
    'notifications.projectId': 'Project ID: {id}...',
    'notifications.loadFailed': 'Failed to load notifications',
    'notifications.markReadFailed': 'Failed to mark notification as read',
    'notifications.markAllReadFailed': 'Failed to mark all notifications as read',
    'notifications.markAllReadSuccess': 'All notifications marked as read',
    
    // Project Comments
    'comments.title': 'Project Comments',
    'comments.subtitle': 'Discuss and collaborate on this project',
    'comments.addComment': 'Add Comment',
    'comments.loading': 'Loading comments...',
    'comments.noComments': 'No comments yet',
    'comments.noCommentsMessage': 'Be the first to start the conversation!',
    'comments.guest': 'Guest',
    'comments.edited': '(edited)',
    'comments.reply': 'Reply',
    'comments.edit': 'Edit',
    'comments.delete': 'Delete',
    'comments.deleteComment': 'Delete Comment',
    'comments.deleteConfirm': 'Are you sure you want to delete this comment? This action cannot be undone.',
    'comments.deleteCommentAction': 'Delete Comment',
    'comments.editComment': 'Edit Comment',
    'comments.editSubtitle': 'Update your comment',
    'comments.replyTo': 'Reply to {name}',
    'comments.replySubtitle': 'Write a reply to this comment.',
    'comments.replyingTo': 'Replying to {name}:',
    'comments.writeComment': 'Write your comment...',
    'comments.replyAction': 'Reply',
    'comments.commentAction': 'Comment',
    'comments.updateComment': 'Update Comment',
    'comments.commentAdded': 'Comment added successfully',
    'comments.commentUpdated': 'Comment updated successfully',
    'comments.commentDeleted': 'Comment deleted successfully',
    'comments.loadFailed': 'Failed to load comments',
    'comments.addFailed': 'Failed to add comment',
    'comments.updateFailed': 'Failed to update comment',
    'comments.deleteFailed': 'Failed to delete comment',
    'comments.pleaseEnterComment': 'Please enter a comment',
    
    // Project Page Additional Translations
    'project.tabs.analysis': 'Analysis',
    'project.tabs.members': 'Members',
    'project.tabs.comments': 'Comments',
    'project.tabs.history': 'History',
    'project.pluginWizard.title': 'Use Plugin Wizard',
    'project.pluginWizard.subtitle': 'This project was created with plugin "{plugin}". Open the wizard to upload another Excel and run analysis.',
    'project.pluginWizard.open': 'Open {plugin} Wizard',
    'project.visibility.public': 'Public',
    'project.visibility.private': 'Private',
    'project.manageMembers': 'Manage Members',
    'project.deleteProject': 'Delete Project',
    'project.deleteConfirm': 'Are you sure you want to delete this project? This action cannot be undone.',
    'project.loading': 'Loading project...',
    'project.notFound': 'Project not found or you don\'t have access to it.',
    'project.visibility.title': 'Visibility',
    'project.visibility.publicDescription': 'Anyone with the link can view this project',
    'project.visibility.privateDescription': 'Only you and project members can view this project',
    'project.memberManagement.title': 'Member Management',
    'project.memberManagement.owner': 'Project Owner',
    'project.memberManagement.yourAccess': 'Your Access',
    'project.memberManagement.ownerAccess': 'Owner (Full Access)',
    'project.memberManagement.memberAccess': 'Member (Limited Access)',
    'project.memberManagement.manageMembers': 'Manage Members',
    'project.memberManagement.ownerDescription': 'As the project owner, you have full control over this project',
    'project.memberManagement.memberDescription': 'Your access permissions are determined by the project owner',
    'project.quickStats.totalRuns': 'Total Runs',
    'project.quickStats.totalImages': 'Total Images',
    'project.quickStats.artifacts': 'Artifacts',
    'project.publicSharing.title': 'Public Sharing',
    'project.publicSharing.subtitle': 'This project is publicly accessible via URL',
    'project.publicSharing.publicUrl': 'Public URL',
    'project.publicSharing.copyLink': 'Copy Link',
    'project.publicSharing.shareDescription': 'Anyone with this link can view the project and its runs',
    'project.publicSharing.serverNotAvailable': 'Server information not available',
    'project.analysisHistory.noRuns': 'No analysis runs yet',
    'project.analysisHistory.images': 'images',
    'project.analysisHistory.startedBy': 'Started by: {email}',
    'project.analysisHistory.view': 'View',
    'project.analysisHistory.download': 'Download',
    'project.analysisHistory.delete': 'Delete',
    'project.analysisHistory.deleteConfirm': 'Are you sure you want to delete this run? This action cannot be undone.',
    'project.analysisHistory.zipDownloaded': 'ZIP file downloaded successfully!',
    'project.analysisHistory.zipDownloadFailed': 'Failed to download ZIP file',
    'project.runDeleted': 'Run deleted successfully!',
    'project.projectUpdated': 'Project updated successfully!',
    'project.projectDeleted': 'Project deleted successfully!',
    'project.analysisStarted': 'Analysis started successfully!',
    'project.runDeletedFailed': 'Run deletion failed',
    'project.projectUpdatedFailed': 'Project update failed',
    'project.projectDeletedFailed': 'Project deletion failed',
    'project.analysisStartedFailed': 'Analysis start failed',
    'project.selectBothFiles': 'Please select both CSV and JSL files',
    'project.uploadUrlsFailed': 'Failed to get upload URLs',
    'project.uploadFilesFailed': 'Failed to upload files',
    'project.startRunFailed': 'Failed to start run',
    'project.copiedToClipboard': 'Copied to clipboard!',
    'project.copyFailed': 'Failed to copy to clipboard',
    
    // Help Illustrations
    'help.illustrations.loginFlow': 'Login Flow',
    'help.illustrations.pluginWorkflow': 'Plugin Workflow',
    'help.illustrations.resultsView': 'Results View',
    'help.illustrations.pluginComparison': 'Plugin Comparison',

    // Project Attachments
    'project.tabs.attachments': 'Attachments',
    'attachments.title': 'Attachments',
    'attachments.loading': 'Loading attachments...',
    'attachments.noAttachments': 'No attachments yet',
    'attachments.noAttachmentsDesc': 'Upload files to share with project members',
    'attachments.upload': 'Upload',
    'attachments.uploadTitle': 'Upload Attachment',
    'attachments.uploadDesc': 'Upload a file to attach to this project. Maximum file size is 200MB.',
    'attachments.file': 'File',
    'attachments.description': 'Description',
    'attachments.descriptionPlaceholder': 'Enter a description for this attachment',
    'attachments.fileLabel': 'File:',
    'attachments.sizeLabel': 'Size:',
    'attachments.cancel': 'Cancel',
    'attachments.download': 'Download',
    'attachments.delete': 'Delete',
    'attachments.deleteConfirm': 'Are you sure you want to delete this attachment?',
    'attachments.uploadSuccess': 'Attachment uploaded successfully',
    'attachments.deleteSuccess': 'Attachment deleted successfully',
    'attachments.uploadFailed': 'Failed to upload attachment',
    'attachments.deleteFailed': 'Failed to delete attachment',
    'attachments.fetchFailed': 'Failed to fetch attachments',
    'attachments.selectFile': 'Please select a file',
    'attachments.provideDescription': 'Please provide a description',
    'attachments.fileSizeExceeded': 'File size must be less than 200MB',
    'attachments.by': 'by',
    'attachments.fileSizeUnits': ['Bytes', 'KB', 'MB', 'GB'],
  },
  zh: {
    // Plugins Listing
    'plugins.list.title': '分析插件',
    'plugins.list.subtitle': '选择一个分析插件来处理您的Excel数据',
    'plugins.list.createProject': '创建新项目',
    'plugins.list.loading': '正在加载插件...',
    'plugins.list.none': '暂无可用插件',
    'plugins.list.backToProjects': '返回项目',

    // Plugins Create Project
    'plugins.create.back': '返回插件列表',
    'plugins.create.title': '使用插件创建项目',
    'plugins.create.subtitle': '选择一个插件并创建项目以开始分析',
    'plugins.create.stepSelect': '1. 选择分析插件',
    'plugins.create.features': '功能：',
    'plugins.create.stepConfigure': '2. 配置项目',
    'plugins.create.details': '项目详情',
    'plugins.create.name': '项目名称',
    'plugins.create.namePlaceholder': '输入项目名称...',
    'plugins.create.description': '描述',
    'plugins.create.descriptionPlaceholder': '输入项目描述...',
    'plugins.create.public': '将此项目设为公开',
    'plugins.create.selected': '已选择插件：',
    'plugins.create.creating': '正在创建项目...',
    'plugins.create.create': '创建项目并开始分析',
    'plugins.create.loading': '加载中...',
    // Plugin Wizard
    'plugin.wizard.upload': '上传Excel文件',
    'plugin.wizard.uploadDesc': '选择并分析您的Excel文件',
    'plugin.wizard.selectVariables': '选择变量',
    'plugin.wizard.selectVariablesDesc': '选择用于分析的分类变量',
    'plugin.wizard.validation': '数据校验',
    'plugin.wizard.validationDesc': '校验结构、元数据和数据质量',
    'plugin.wizard.boundary': '边界计算',
    'plugin.wizard.boundaryDesc': '计算最小值、最大值、步长和刻度',
    'plugin.wizard.processing': '文件处理',
    'plugin.wizard.processingDesc': '生成CSV和JSL文件',
    'plugin.wizard.run': '运行分析',
    'plugin.wizard.runDesc': '监控您的分析进度',
    'plugin.wizard.selectExcel': '选择Excel文件',
    'plugin.wizard.analyzeFile': '分析文件',
    'plugin.wizard.selectCatVar': '选择分类变量',
    'plugin.wizard.selectCatVarDesc': '选择用于分组分析数据的分类变量。',
    'plugin.wizard.fileAnalysis': '文件分析结果：',
    'plugin.wizard.catVar': '分类变量：',
    'plugin.wizard.catVarHint': '该变量将用于在图表中分组数据。',
    'plugin.wizard.noCatVar': '未找到分类变量',
    'plugin.wizard.noCatVarDesc': '系统无法自动识别分类变量，请检查Excel结构或手动指定。',
    'plugin.wizard.continueValidation': '继续进行校验',
    'plugin.wizard.validateFile': '校验文件',
    'plugin.wizard.viewDetails': '查看详情',
    'plugin.wizard.continueBoundary': '继续进行边界计算',
    'plugin.wizard.boundaryLong': '根据数据和规格计算最小/最大/步长/刻度。',
    'plugin.wizard.thisStep': '本步骤将：',
    'plugin.wizard.stepAnalyze': '分析数据范围和USL/LSL规格',
    'plugin.wizard.stepMinMax': '计算图表的最佳最小/最大值',
    'plugin.wizard.stepInc': '确定合适的步长（inc）',
    'plugin.wizard.stepTick': '设置更好的刻度间隔',
    'plugin.wizard.calculate': '计算边界',
    'plugin.wizard.boundaryResults': '边界计算结果：',
    'plugin.wizard.processingDots': '处理中...',
    'plugin.wizard.processFiles': '处理文件',
    'plugin.wizard.running': '分析运行中',
    'plugin.wizard.runningDesc': '您的分析正在运行。您可以在运行列表中监控进度。',
    'plugin.wizard.status': '分析状态',
    'plugin.wizard.clickStart': '点击“开始分析”以启动。',
    'plugin.wizard.runId': '运行ID',
    'plugin.wizard.runStatus': '运行状态',
    'plugin.wizard.starting': '启动中...',
    'plugin.wizard.start': '开始分析',
    'plugin.wizard.goToProject': '前往项目页面',
    // Common
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.delete': '删除',
    'common.confirm': '确认',
    'common.back': '返回',
    'common.next': '下一步',
    'common.previous': '上一步',
    'common.close': '关闭',
    'common.yes': '是',
    'common.no': '否',
    'common.ok': '确定',
    
    // Navigation
    'nav.dashboard': '仪表板',
    'nav.profile': '个人资料',
    'nav.profileSettings': '个人资料设置',
    'nav.logout': '退出登录',
    'nav.language': '语言',
    
    // Auth
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.guest': '游客继续',
    'auth.welcome': '欢迎回来',
    'auth.guestWelcome': '欢迎回来（游客）',
    'auth.loginTitle': '登录您的账户',
    'auth.registerTitle': '创建新账户',
    'auth.loginSubtitle': '登录以访问您的项目和分析结果',
    'auth.registerSubtitle': '创建账户以开始分析数据',
    'auth.signingIn': '登录中...',
    'auth.creatingAccount': '创建账户中...',
    'auth.creatingGuest': '创建游客会话中...',
    'auth.alreadyHaveAccount': '已有账户？',
    'auth.dontHaveAccount': '没有账户？',
    'auth.switchToLogin': '切换到登录',
    'auth.switchToRegister': '切换到注册',
    'auth.tryAsGuest': '游客试用',
    'auth.guestDescription': '无需创建账户即可体验平台',
    'auth.guestWarning': '游客访问功能有限且文件大小受限。创建账户以获得完整访问权限。',
    
    // Profile
    'profile.title': '个人资料设置',
    'profile.subtitle': '管理您的账户设置和偏好',
    'profile.notAvailable': '个人资料设置不可用',
    'profile.guestMessage': '游客用户无法访问个人资料设置。请创建账户以管理您的个人资料。',
    'profile.goHome': '返回首页',
    'profile.tabs.profile': '个人资料',
    'profile.tabs.security': '安全',
    'profile.tabs.danger': '危险区域',
    'profile.info.title': '个人资料信息',
    'profile.info.subtitle': '更新您的个人资料信息和账户详情',
    'profile.info.accountId': '账户ID',
    'profile.info.accountType': '账户类型',
    'profile.info.memberSince': '注册时间',
    'profile.info.lastLogin': '最后登录',
    'profile.info.administrator': '管理员',
    'profile.info.regularUser': '普通用户',
    'profile.info.emailAddress': '邮箱地址',
    'profile.info.updateEmail': '更新邮箱',
    'profile.info.updating': '更新中...',
    'profile.security.title': '修改密码',
    'profile.security.subtitle': '更新您的密码以保护账户安全',
    'profile.security.currentPassword': '当前密码',
    'profile.security.newPassword': '新密码',
    'profile.security.confirmPassword': '确认新密码',
    'profile.security.changePassword': '修改密码',
    'profile.security.changingPassword': '修改密码中...',
    'profile.security.requirements': '密码要求：',
    'profile.security.requirements.minLength': '至少8个字符',
    'profile.security.requirements.different': '必须与当前密码不同',
    'profile.danger.title': '危险区域',
    'profile.danger.subtitle': '不可逆的破坏性操作',
    'profile.danger.deleteAccount': '删除账户',
    'profile.danger.deleteWarning': '一旦删除您的账户，将无法恢复。这将永久删除您的账户并从我们的服务器中移除所有数据。',
    'profile.danger.deletingAccount': '删除账户中...',
    
    // Dashboard
    'dashboard.title': '数据分析平台',
    'dashboard.welcome': '欢迎回来',
    'dashboard.guestWelcome': '欢迎回来（游客）',
    'dashboard.subtitle': '管理您的项目并查看分析结果。',
    'dashboard.stats.totalProjects': '总项目数',
    'dashboard.stats.totalRuns': '总运行数',
    'dashboard.stats.activeRuns': '活跃运行',
    'dashboard.projects.title': '您的项目',
    'dashboard.projects.newProject': '新建项目',
    'dashboard.projects.noProjects': '暂无项目',
    'dashboard.projects.noProjectsMessage': '创建您的第一个项目以开始使用JMP分析数据。',
    'dashboard.projects.createFirst': '创建您的第一个项目',
    'dashboard.projects.createNew': '新建项目',
    'dashboard.projects.createSubtitle': '创建新项目以组织您的数据分析任务',
    'dashboard.projects.projectName': '项目名称',
    'dashboard.projects.projectDescription': '描述（可选）',
    'dashboard.projects.makePublic': '将此项目设为公开（可通过URL访问）',
    'dashboard.projects.creating': '创建中...',
    'dashboard.projects.createProject': '创建项目',
    'dashboard.projects.public': '公开',
    'dashboard.projects.private': '私有',
    'dashboard.projects.runs': '运行',
    'dashboard.projects.lastRun': '最后运行',
    'dashboard.projects.viewProject': '查看项目',
    'dashboard.runs.title': '最近运行',
    'dashboard.runs.noRuns': '暂无最近运行',
    'dashboard.runs.noRunsMessage': '开始您的第一次分析以在此处查看运行历史。',
    'dashboard.welcomeMessage': '管理您的项目并查看分析结果。',
    'dashboard.enterProjectName': '输入项目名称',
    'dashboard.enterProjectDescription': '输入项目描述',
    
    // Projects
    'projects.backToDashboard': '返回仪表板',
    'projects.startAnalysis': '开始新分析',
    'projects.startAnalysisSubtitle': '上传您的CSV数据文件和JSL脚本以生成箱线图可视化',
    'projects.csvFile': 'CSV数据文件',
    'projects.jslFile': 'JSL脚本文件',
    'projects.selectFile': '选择文件',
    'projects.noFileSelected': '未选择文件',
    'projects.startRun': '开始分析',
    'projects.starting': '开始中...',
    'projects.analysisHistory': '分析历史',
    'projects.loadingRuns': '加载运行中...',
    'projects.noRuns': '暂无运行',
    'projects.noRunsMessage': '上传文件并开始您的第一次分析。',
    'projects.runStatus.queued': '排队中',
    'projects.runStatus.running': '运行中',
    'projects.runStatus.succeeded': '成功',
    'projects.runStatus.failed': '失败',
    'projects.runStatus.canceled': '已取消',
    'projects.downloadResults': '下载结果',
    'projects.viewImages': '查看图片',
    'projects.deleteRun': '删除运行',
    'projects.projectDetails': '项目详情',
    'projects.owner': '所有者',
    'projects.unknown': '未知',
    'projects.created': '创建时间',
    'projects.quickStats': '快速统计',
    'projects.publicSharing': '公开分享',
    'projects.publicSharingSubtitle': '此项目可通过URL公开访问',
    'projects.publicUrl': '公开URL',
    'projects.copyLink': '复制公开链接',
    'projects.copied': '已复制到剪贴板！',
    'projects.deleteProject': '删除项目',
    'projects.deleteConfirm': '您确定要删除此项目吗？此操作无法撤销。',
    
    // Messages
    'messages.passwordChanged': '密码修改成功',
    'messages.profileUpdated': '个人资料更新成功',
    'messages.accountDeleted': '账户删除成功',
    'messages.emailRequired': '邮箱是必需的',
    'messages.emailSame': '邮箱与当前邮箱相同',
    'messages.passwordRequired': '所有密码字段都是必需的',
    'messages.passwordMismatch': '新密码不匹配',
    'messages.passwordTooShort': '新密码必须至少8个字符',
    'messages.currentPasswordIncorrect': '当前密码不正确',
    'messages.emailAlreadyExists': '邮箱已注册',
    'messages.guestCannotChangePassword': '游客用户无法修改密码',
    'messages.guestCannotUpdateProfile': '游客用户无法更新个人资料信息',
    'messages.adminCannotDelete': '管理员账户无法删除',
    'messages.projectCreated': '项目创建成功！',
    'messages.projectDeleted': '项目删除成功！',
    'messages.runStarted': '分析开始成功！',
    'messages.runDeleted': '运行删除成功！',
    'messages.fileUploaded': '文件上传成功！',
    'messages.copyFailed': '复制到剪贴板失败',
    'messages.downloadFailed': '下载失败',
    'messages.uploadFailed': '上传失败',
    'messages.analysisFailed': '分析失败',
    'messages.authenticationFailed': '身份验证失败',
    
    // Plugin Cards
    'plugin.card.supportedFormats': '支持格式：',
    'plugin.card.usePlugin': '使用插件',
    'plugin.card.version': '版本',
    
    // Plugin Names and Descriptions
    'plugin.excel2boxplotv1.name': 'Excel转箱线图 V1',
    'plugin.excel2boxplotv1.description': '将Excel文件转换为CSV和JSL脚本，具有三点验证系统',
    'plugin.excel2boxplotv2.name': 'Excel转箱线图 V2',
    'plugin.excel2boxplotv2.description': 'Excel转CSV/JSL，使用V2列映射',
    'plugin.excel2processcapability.name': 'Excel转过程能力分析',
    'plugin.excel2processcapability.description': '将Excel数据转换为过程能力分析（Cp、Cpk、Pp、Ppk）',
    
    // Plugin Categories
    'plugin.category.analysis': '分析',
    'plugin.category.statistics': '统计',
    
    // Plugin Features
    'plugin.excel2boxplotv1.features.0': '三点验证系统',
    'plugin.excel2boxplotv1.features.1': '自动修复损坏的Excel文件',
    'plugin.excel2boxplotv1.features.2': '边界计算（最小值、最大值、步长、刻度）',
    'plugin.excel2boxplotv1.features.3': 'CSV和JSL生成',
    'plugin.excel2boxplotv1.features.4': '箱线图可视化',
    'plugin.excel2boxplotv2.features.0': 'V2元列映射（Y变量/DETAIL/目标/USL/LSL/标签）',
    'plugin.excel2boxplotv2.features.1': '优先使用Stage作为分类变量',
    'plugin.excel2boxplotv2.features.2': '三点验证（信息性）',
    'plugin.excel2boxplotv2.features.3': '边界计算（最小值、最大值、步长、刻度）',
    'plugin.excel2boxplotv2.features.4': 'CSV和JSL生成',
    'plugin.excel2processcapability.features.0': '过程能力分析',
    'plugin.excel2processcapability.features.1': '统计过程控制',
    'plugin.excel2processcapability.features.2': '能力指数计算',
    'plugin.excel2processcapability.features.3': '控制图生成',
    
    // Admin Plugin Management
    'admin.plugins.title': '插件管理',
    'admin.plugins.subtitle': '管理已安装的插件及其描述',
    'admin.plugins.backToDashboard': '返回仪表板',
    'admin.plugins.install': '安装',
    'admin.plugins.uninstall': '卸载',
    'admin.plugins.editEnglish': '编辑英文',
    'admin.plugins.editChinese': '编辑中文',
    'admin.plugins.save': '保存',
    'admin.plugins.cancel': '取消',
    'admin.plugins.addFeature': '添加功能',
    'admin.plugins.supportedFormats': '支持格式：',
    'admin.plugins.installed': '已安装',
    'admin.plugins.available': '可用',
    'admin.plugins.features': '功能特性：',
    'admin.plugins.name': '名称',
    'admin.plugins.description': '描述',
    'admin.plugins.featuresLabel': '功能特性',
    'admin.plugins.chineseFeatures': '功能特性：',
    'admin.plugins.chineseName': '名称',
    'admin.plugins.chineseDescription': '描述',
    'admin.plugins.chineseAddFeature': '添加功能',
    'admin.plugins.chineseSave': '保存',
    'admin.plugins.chineseCancel': '取消',
    'admin.plugins.chineseEdit': '编辑中文',
    'admin.plugins.englishEdit': '编辑英文',
    
    // Landing Page
    'landing.title': '数据分析平台',
    'landing.subtitle': '上传您的CSV和JSL文件，使用JMP生成美观的箱线图可视化。实时处理、交互式画廊和无缝分享。',
    'landing.features.easyUpload.title': '轻松上传',
    'landing.features.easyUpload.description': '拖放您的CSV和JSL文件进行即时分析',
    'landing.features.realTime.title': '实时处理',
    'landing.features.realTime.description': '通过实时更新观看您的分析进度',
    'landing.features.share.title': '分享与协作',
    'landing.features.share.description': '与团队成员分享您的结果或创建公开链接',
    
    // Help
    'help.title': '帮助',
    'help.center': '帮助中心',
    'help.overview': '平台概述',
    'help.gettingStarted': '入门指南',
    'help.plugins': '可用插件',
    'help.troubleshooting': '故障排除',
    'help.support': '支持与联系',
    'help.navigation': '导航',
    'help.back': '返回',
    
    // Dashboard Additional Translations
    'dashboard.createProject.title': '创建新项目',
    'dashboard.createProject.subtitle': '创建新项目以组织您的数据分析任务',
    'dashboard.createProject.projectName': '项目名称',
    'dashboard.createProject.description': '描述（可选）',
    'dashboard.createProject.makePublic': '将此项目设为公开（可通过URL访问）',
    'dashboard.createProject.creating': '创建中...',
    'dashboard.createProject.create': '创建项目',
    'dashboard.createProject.cancel': '取消',
    'dashboard.stats.activeProjects': '活跃项目',
    'dashboard.stats.totalAnalyses': '总分析数',
    'dashboard.stats.currentlyProcessing': '正在处理',
    'dashboard.projects.noProjects.title': '暂无项目',
    'dashboard.projects.noProjects.message': '创建您的第一个项目以开始使用JMP分析数据。上传Excel文件并生成美观的可视化。',
    'dashboard.plugins.title': '分析插件',
    'dashboard.plugins.excelPlugins.title': 'Excel分析插件',
    'dashboard.plugins.excelPlugins.description': '将Excel文件转换为统计分析和可视化',
    'dashboard.plugins.excelPlugins.viewAll': '查看所有插件',
    'dashboard.plugins.quickAnalysis.title': '快速箱线图分析',
    'dashboard.plugins.quickAnalysis.description': '上传Excel文件并立即生成箱线图分析',
    'dashboard.plugins.quickAnalysis.start': '开始箱线图分析',
    'dashboard.recentRuns.title': '最近运行',
    
    // Project Membership Management
    'membership.title': '项目成员',
    'membership.subtitle': '管理项目成员及其角色。',
    'membership.viewOnly.subtitle': '您可以查看项目成员但无法管理他们。',
    'membership.tabs.current': '当前成员',
    'membership.tabs.add': '添加成员',
    'membership.searchUsers': '搜索用户',
    'membership.searchPlaceholder': '按邮箱或姓名搜索...',
    'membership.role': '角色',
    'membership.filterDepartment': '按部门筛选',
    'membership.filterBusinessGroup': '按业务组筛选',
    'membership.allDepartments': '所有部门',
    'membership.allBusinessGroups': '所有业务组',
    'membership.searchResults': '搜索结果',
    'membership.searching': '搜索中...',
    'membership.noUsersFound': '未找到用户',
    'membership.enterSearchTerm': '输入搜索词以查找用户',
    'membership.alreadyMember': '已是成员',
    'membership.add': '添加',
    'membership.owner': '所有者',
    'membership.member': '成员',
    'membership.watcher': '观察者',
    'membership.removeMember': '移除成员',
    'membership.removeConfirm': '您确定要从此项目中移除 {name} 吗？',
    'membership.remove': '移除',
    'membership.roleUpdated': '成员角色更新成功',
    'membership.memberRemoved': '成员移除成功',
    'membership.memberAdded': '已添加 {name} 为 {role}',
    'membership.loadMembersFailed': '加载成员失败',
    'membership.searchUsersFailed': '搜索用户失败',
    'membership.addMemberFailed': '添加成员失败',
    'membership.updateRoleFailed': '更新成员角色失败',
    'membership.removeMemberFailed': '移除成员失败',
    
    // Notifications
    'notifications.title': '通知',
    'notifications.subtitle': '了解项目活动和团队变化。',
    'notifications.markAllRead': '全部标记为已读',
    'notifications.loading': '加载通知中...',
    'notifications.noNotifications': '暂无通知',
    'notifications.noNotificationsMessage': '您将在此处看到项目更新',
    'notifications.justNow': '刚刚',
    'notifications.minutesAgo': '{minutes}分钟前',
    'notifications.hoursAgo': '{hours}小时前',
    'notifications.daysAgo': '{days}天前',
    'notifications.projectId': '项目ID: {id}...',
    'notifications.loadFailed': '加载通知失败',
    'notifications.markReadFailed': '标记为已读失败',
    'notifications.markAllReadFailed': '全部标记为已读失败',
    'notifications.markAllReadSuccess': '所有通知已标记为已读',
    
    // Project Comments
    'comments.title': '项目评论',
    'comments.subtitle': '讨论并协作此项目',
    'comments.addComment': '添加评论',
    'comments.loading': '加载评论中...',
    'comments.noComments': '暂无评论',
    'comments.noCommentsMessage': '成为第一个开始对话的人！',
    'comments.guest': '游客',
    'comments.edited': '（已编辑）',
    'comments.reply': '回复',
    'comments.edit': '编辑',
    'comments.delete': '删除',
    'comments.deleteComment': '删除评论',
    'comments.deleteConfirm': '您确定要删除此评论吗？此操作无法撤销。',
    'comments.deleteCommentAction': '删除评论',
    'comments.editComment': '编辑评论',
    'comments.editSubtitle': '更新您的评论',
    'comments.replyTo': '回复 {name}',
    'comments.replySubtitle': '写一个回复。',
    'comments.replyingTo': '回复 {name}:',
    'comments.writeComment': '写您的评论...',
    'comments.replyAction': '回复',
    'comments.commentAction': '评论',
    'comments.updateComment': '更新评论',
    'comments.commentAdded': '评论添加成功',
    'comments.commentUpdated': '评论更新成功',
    'comments.commentDeleted': '评论删除成功',
    'comments.loadFailed': '加载评论失败',
    'comments.addFailed': '添加评论失败',
    'comments.updateFailed': '更新评论失败',
    'comments.deleteFailed': '删除评论失败',
    'comments.pleaseEnterComment': '请输入评论',
    
    // Project Page Additional Translations
    'project.tabs.analysis': '分析',
    'project.tabs.members': '成员',
    'project.tabs.comments': '评论',
    'project.tabs.history': '历史',
    'project.pluginWizard.title': '使用插件向导',
    'project.pluginWizard.subtitle': '此项目是使用插件"{plugin}"创建的。打开向导上传另一个Excel并运行分析。',
    'project.pluginWizard.open': '打开 {plugin} 向导',
    'project.visibility.public': '公开',
    'project.visibility.private': '私有',
    'project.manageMembers': '管理成员',
    'project.deleteProject': '删除项目',
    'project.deleteConfirm': '您确定要删除此项目吗？此操作无法撤销。',
    'project.loading': '加载项目中...',
    'project.notFound': '未找到项目或您无权访问。',
    'project.visibility.title': '可见性',
    'project.visibility.publicDescription': '任何有链接的人都可以查看此项目',
    'project.visibility.privateDescription': '只有您和项目成员可以查看此项目',
    'project.memberManagement.title': '成员管理',
    'project.memberManagement.owner': '项目所有者',
    'project.memberManagement.yourAccess': '您的访问权限',
    'project.memberManagement.ownerAccess': '所有者（完全访问）',
    'project.memberManagement.memberAccess': '成员（有限访问）',
    'project.memberManagement.manageMembers': '管理成员',
    'project.memberManagement.ownerDescription': '作为项目所有者，您对此项目拥有完全控制权',
    'project.memberManagement.memberDescription': '您的访问权限由项目所有者确定',
    'project.quickStats.totalRuns': '总运行数',
    'project.quickStats.totalImages': '总图片数',
    'project.quickStats.artifacts': '工件',
    'project.publicSharing.title': '公开分享',
    'project.publicSharing.subtitle': '此项目可通过URL公开访问',
    'project.publicSharing.publicUrl': '公开URL',
    'project.publicSharing.copyLink': '复制链接',
    'project.publicSharing.shareDescription': '任何有此链接的人都可以查看项目及其运行',
    'project.publicSharing.serverNotAvailable': '服务器信息不可用',
    'project.analysisHistory.noRuns': '暂无分析运行',
    'project.analysisHistory.images': '图片',
    'project.analysisHistory.startedBy': '开始者: {email}',
    'project.analysisHistory.view': '查看',
    'project.analysisHistory.download': '下载',
    'project.analysisHistory.delete': '删除',
    'project.analysisHistory.deleteConfirm': '您确定要删除此运行吗？此操作无法撤销。',
    'project.analysisHistory.zipDownloaded': 'ZIP文件下载成功！',
    'project.analysisHistory.zipDownloadFailed': '下载ZIP文件失败',
    'project.runDeleted': '运行删除成功！',
    'project.projectUpdated': '项目更新成功！',
    'project.projectDeleted': '项目删除成功！',
    'project.analysisStarted': '分析开始成功！',
    'project.runDeletedFailed': '运行删除失败',
    'project.projectUpdatedFailed': '项目更新失败',
    'project.projectDeletedFailed': '项目删除失败',
    'project.analysisStartedFailed': '分析开始失败',
    'project.selectBothFiles': '请选择CSV和JSL文件',
    'project.uploadUrlsFailed': '获取上传URL失败',
    'project.uploadFilesFailed': '上传文件失败',
    'project.startRunFailed': '开始运行失败',
    'project.copiedToClipboard': '已复制到剪贴板！',
    'project.copyFailed': '复制到剪贴板失败',
    
    // Help Illustrations
    'help.illustrations.loginFlow': '登录流程',
    'help.illustrations.pluginWorkflow': '插件工作流',
    'help.illustrations.resultsView': '结果查看',
    'help.illustrations.pluginComparison': '插件比较',

    // Project Attachments
    'project.tabs.attachments': '附件',
    'attachments.title': '附件',
    'attachments.loading': '正在加载附件...',
    'attachments.noAttachments': '暂无附件',
    'attachments.noAttachmentsDesc': '上传文件与项目成员分享',
    'attachments.upload': '上传',
    'attachments.uploadTitle': '上传附件',
    'attachments.uploadDesc': '上传文件附加到此项目。最大文件大小为200MB。',
    'attachments.file': '文件',
    'attachments.description': '描述',
    'attachments.descriptionPlaceholder': '为此附件输入描述',
    'attachments.fileLabel': '文件：',
    'attachments.sizeLabel': '大小：',
    'attachments.cancel': '取消',
    'attachments.download': '下载',
    'attachments.delete': '删除',
    'attachments.deleteConfirm': '您确定要删除此附件吗？',
    'attachments.uploadSuccess': '附件上传成功',
    'attachments.deleteSuccess': '附件删除成功',
    'attachments.uploadFailed': '附件上传失败',
    'attachments.deleteFailed': '附件删除失败',
    'attachments.fetchFailed': '获取附件失败',
    'attachments.selectFile': '请选择文件',
    'attachments.provideDescription': '请提供描述',
    'attachments.fileSizeExceeded': '文件大小必须小于200MB',
    'attachments.by': '由',
    'attachments.fileSizeUnits': ['字节', 'KB', 'MB', 'GB'],
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')
  const { getPluginDescription } = usePluginDescriptions()

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'zh')) {
      setLanguage(savedLanguage)
    }
  }, [])

  // Save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('language', language)
  }, [language])

  const t = (key: string, params?: Record<string, any>): string => {
    // Check if this is a plugin description key
    if (key.startsWith('plugin.') && key.includes('.name')) {
      const pluginId = key.split('.')[1]
      const dynamicName = getPluginDescription(pluginId, language, 'name', '')
      if (dynamicName !== undefined) return dynamicName as string
    }
    
    if (key.startsWith('plugin.') && key.includes('.description')) {
      const pluginId = key.split('.')[1]
      const dynamicDesc = getPluginDescription(pluginId, language, 'description', '')
      if (dynamicDesc !== undefined) return dynamicDesc as string
    }
    
    if (key.startsWith('plugin.') && key.includes('.features.')) {
      const parts = key.split('.')
      const pluginId = parts[1]
      const featureIndex = parseInt(parts[3])
      const dynamicFeatures = getPluginDescription(pluginId, language, 'features', [])
      if (dynamicFeatures && Array.isArray(dynamicFeatures) && dynamicFeatures[featureIndex]) {
        return dynamicFeatures[featureIndex] as string
      }
    }

    // Fall back to hardcoded translations
    let translation: any = translations[language][key as keyof typeof translations[typeof language]] || key
    
    // Handle parameter interpolation only for strings
    if (params && typeof translation === 'string') {
      Object.keys(params).forEach(paramKey => {
        translation = translation.replace(new RegExp(`{${paramKey}}`, 'g'), params[paramKey])
      })
    }
    
    return translation
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
